apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronicas-app-dev
  labels:
    app: cronicas-app-dev
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: cronicas-app-dev
  template:
    metadata:
      labels:
        app: cronicas-app-dev
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: cronicas-app-dev
          image: ghcr.io/masneto/cronicas-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: NODE_ENV
              value: "production"
