name: "[Cronicas] CI Actions"

run-name: "Build Actions #${{ github.run_number }} by ${{ github.actor }} "

on:
  push:
    branches:
      - "feature/*"
    paths:
      - ".github/actions/**"

jobs:
  validate-and-build-actions:
    name: Validate & Build Changed Actions
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Identify Changed Actions
        id: changed-actions
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^\.github/actions/' | cut -d'/' -f1-3 | sort -u || true)
          echo "Found changed action directories:"
          echo "$CHANGED_DIRS"
          echo "actions=$CHANGED_DIRS" >> "$GITHUB_ENV"

      - name: Process Actions and Commit Changes
        if: env.actions != ''
        run: |
          for action in ${{ env.actions }}; do
            echo "::group::Processing $action"
            cd "$action"

            if [ -f package.json ]; then
              echo "Installing dependencies..."
              npm ci

              echo "Running linter..."
              npm run lint

              echo "Running tests..."
              npm test

              echo "Building action..."
              npm run build
            else
              echo "Skipping $action (no package.json found)"
            fi

            cd - > /dev/null
            echo "::endgroup::"
          done

      - name: Listar arquivos depois do build
        run: ls -lah .github/actions/**/dist/

      - name: Commit and Push Dist Changes
        if: env.actions != ''
        continue-on-error: true
        run: |
          echo "::group::Commit and Push Dist Changes"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização de build da(s) action(s): ${{ env.actions }}"
          git push https://x-access-token:${{ secrets.PAT_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }} --force
          echo "::endgroup::"

  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    if: failure()
    needs: validate-and-build-actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get Failed Job
        id: get-failed-job
        run: |
          echo "JOB_NAME=$(jq -r 'to_entries[] | select(.value.result == "failure") | .key' <<< '${{ toJson(needs) }}')" >> $GITHUB_ENV
          echo "ERROR_MESSAGE=$(jq -r 'to_entries[] | select(.value.result == "failure") | .value.outputs.error_message // "No error message provided"' <<< '${{ toJson(needs) }}')" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: ./.github/actions/email-notification-action
        with:
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
          subject: "[CRÔNICAS ALERTAS]🚨 Falha no Workflow ${{ github.workflow }}"
          workflow_name: ${{ github.workflow }}
          branch: ${{ github.ref_name }}
          author_name: ${{ github.actor }}
          run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          error_message: "Job com falha: ${{ env.JOB_NAME }} - Mensagem: ${{ env.ERROR_MESSAGE }}"