name: "[Cronicas] Create Pull Request"

run-name: "Create PR to main. #${{ github.run_number }} by ${{ github.actor }}"

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "commit_type=$(echo '${{ github.event.head_commit.message }}' | cut -d ':' -f 1)" >> GITHUB_ENV

    - run: |
       echo "commit_type: ${{ env.commit_type }}" 

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        base: main
        branch: ${{ github.ref }}
        title: '[${{ env.commit_type }}] PR criado automaticamente -> main'
        body: 'This PR was automatically created by GitHub Actions.'
        draft: false

    - name: TESTE IF
      if: ${{ !contains(github.event.head_commit.message, 'cnv-deploy') }}
      run: |
        echo "cnv-deploy não encontrado na mensagem do commit: ${{ github.event.head_commit.message }}"
