name: "[Cronicas] Development CI/CD"

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  bump-version:
    name: Cronicas Bump Version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.tag.outputs.new_version }}
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag_prefix: "v"
          github_token: ${{ secrets.PAT_GITHUB_TOKEN }}
          release_branches: 'develop'
          dry_run: true

      - name: Output the new version
        run: |
          echo "New tag: ${{ steps.tag.outputs.new_tag }}"
          echo "Previous tag: ${{ steps.tag.outputs.previous_tag }}"

  ci:
    name: Cronicas CI
    needs: bump-version
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      version: ${{ needs.bump-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Validate Repository Structure
        uses: ./.github/actions/validate-repo

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Login GitHub Container Registry
        run: |
          echo ${{ secrets.PAT_GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build e Push para o GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/cronicas-app
          docker build -t $IMAGE_NAME:${{ env.version }} .
          docker tag $IMAGE_NAME:${{ env.version }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ env.version }}
          docker push $IMAGE_NAME:latest

  cd:
    name: Cronicas CD
    needs: [bump-version, ci]
    runs-on: ubuntu-latest
    if: always() && success()
    permissions: write-all
    environment:
      name: development
    env:
      version: ${{ needs.bump-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy and Run Docker Image
        run: |
          export VERSION=${{ env.version }}
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"InstanceIds","Values":["${{ secrets.EC2_INSTANCE_ID }}"]}]' \
            --parameters "commands=[
              \"echo ${{ secrets.PAT_GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin\",
              \"docker pull ghcr.io/${{ github.repository_owner }}/cronicas-app:$VERSION\",
              \"docker stop cronicas-app || true\",
              \"docker rm cronicas-app || true\",
              \"docker run -d -p 3000:3000 --name cronicas-app ghcr.io/${{ github.repository_owner }}/cronicas-app:$VERSION\"
            ]" \
            --region sa-east-1

  create-release-pr:
    name: Cronicas PR to Release
    needs: [bump-version, ci, cd]
    runs-on: ubuntu-latest
    if: always() && success()
    permissions: write-all
    env:
      version: ${{ needs.bump-version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main        

      - name: Criar Branch release/v${{ env.version }}
        run: |
          echo "Criando a branch... release/v${{ env.version }}. "
          git checkout main && git pull
          git checkout -b release/v${{ env.version }}
          git push origin release/v${{ env.version }}

      - name: Criar PR para release/v${{ env.version }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          script: |
            const base = `release/v${{ env.version }}`;
            const head = 'develop';
            const title = `[HOM] PR criado automaticamente -> ${base} | by ${context.actor}`;
            const body = 'This PR was automatically created by GitHub Actions.';

            const { data: existingPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base,
              head,
            });

            if (existingPRs.length > 0) {
              console.log(`Pull Request jรก existe: ${existingPRs[0].html_url}`);
            } else {
              const { data: pullRequest } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base,
                head,
                title,
                body,
              });

              console.log(`Pull Request criado com sucesso: ${pullRequest.html_url}`);
            }