name: "[Cronicas] Notify Failure"

on:
  workflow_run:
    workflows:
      - "[Cronicas] CI Actions"
      - "[Cronicas] Create Pull Request"
      - "[Cronicas] Development CI/CD"
      - "[Cronicas] Homologation CD"
      - "[Cronicas] Production CD"
      - "[Cronicas] Release Tag"
    types:
      - completed

jobs:
  notify-failure:
    name: Send Failure Notification
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'cancelled' }}
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CRÔNICAS ALERTAS]🚨 Falha no Workflow ${{ github.event.workflow_run.name }}"
          body: |

            O pipeline de CI/CD falhou. Por favor, verifique os logs no GitHub Actions.
            📌 Workflow: ${{ github.event.workflow_run.name }}
            📌 Repositório: ${{ github.repository }}
            📌 Branch: ${{ github.event.workflow_run.head_branch }}
            📌 Autor: ${{ github.event.workflow_run.head_commit.author.name }} - ${{ github.event.workflow_run.head_commit.author.email }}
            🔗 Logs: ${{ github.event.workflow_run.html_url }}

          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
