name: "[Cronicas] Notify Failure"

on:
  workflow_call:
    inputs:
      workflow_name:
        description: "Nome do workflow que falhou"
        required: true
        type: string
      branch:
        description: "Branch do workflow que falhou"
        required: true
        type: string
      html_url:
        description: "URL dos logs do workflow"
        required: true
        type: string
      author_name:
        description: "Nome do autor do commit"
        required: false
        type: string
      author_email:
        description: "E-mail do autor do commit"
        required: false
        type: string

jobs:
  notify-failure:
    name: Send Failure Notification
    runs-on: ubuntu-latest
    steps:
      - name: Debug Workflow Inputs
        run: |
          echo "Workflow Name: ${{ inputs.workflow_name }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Logs URL: ${{ inputs.html_url }}"
          echo "Author Name: ${{ inputs.author_name }}"
          echo "Author Email: ${{ inputs.author_email }}"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CRÔNICAS ALERTAS]🚨 Falha no Workflow ${{ inputs.workflow_name }}"
          body: |

            O pipeline de CI/CD falhou. Por favor, verifique os logs no GitHub Actions.
            📌 Workflow: ${{ inputs.workflow_name }}
            📌 Repositório: ${{ github.repository }}
            📌 Branch: ${{ inputs.branch }}
            📌 Autor: ${{ inputs.author_name }} - ${{ inputs.author_email }}
            🔗 Logs: ${{ inputs.html_url }}

          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
